<?php
/*
  Datos de proyectos (fuente única): los usan Featured Projects y la franja
  de proyectos del Home.
  ⚠️ TODO CLIENTE: son proyectos DE MUESTRA para maquetar. Antes de publicar,
  reemplazar con los proyectos reales (datos + permisos de builders/arquitectos).
*/

$omega_projects = array(
  array(
    'title'     => 'Hillside Custom Estate',
    'category'  => 'Luxury Residential',
    'location'  => 'Orange County, CA',
    'scope'     => 'Full roof truss system, engineered + delivered',
    'sqft'      => '8,400 sq ft',
    'completion'=> '[Year]',
    'builder'   => '[Builder name]',
    'architect' => '[Architect name]',
    'challenge' => 'Mixed-pitch vaulted roof over a stepped hillside foundation, with seismic and wind loads that pushed standard span tables past their limits.',
    'solution'  => 'Site-specific load engineering with custom scissor and coffer systems, delivered plan-check-ready and staged in sequence with the framer.',
    'img'       => '/wp-content/uploads/2026/08/Project1.jpg',
  ),
  array(
    'title'     => 'Coastal Modern Residence',
    'category'  => 'Luxury Residential',
    'location'  => 'San Diego County, CA',
    'scope'     => 'Roof + floor trusses',
    'sqft'      => '6,100 sq ft',
    'completion'=> '[Year]',
    'builder'   => '[Builder name]',
    'architect' => '[Architect name]',
    'challenge' => 'Long open-plan spans with coastal exposure requirements and an architect determined to keep every ceiling line clean.',
    'solution'  => 'Open-web floor systems engineered for vibration performance, with corrosion-conscious detailing for coastal exposure.',
    'img'       => '/wp-content/uploads/2026/08/Project02.jpg',
  ),
  array(
    'title'     => 'Fire Zone Mountain Build',
    'category'  => 'Fire Zone',
    'location'  => 'Riverside County, CA',
    'scope'     => 'Fire-zone engineered roof system',
    'sqft'      => '4,700 sq ft',
    'completion'=> '[Year]',
    'builder'   => '[Builder name]',
    'architect' => '[Architect name]',
    'challenge' => 'Wildfire-designated zone with strict ignition-resistance requirements and a plan checker known for sending packages back.',
    'solution'  => 'Fire-zone engineering from day one — the package cleared plan check without a single structural comment.',
    'img'       => '/wp-content/uploads/2026/08/Project03.jpg',
  ),
  array(
    'title'     => 'Multifamily Development, Phase I',
    'category'  => 'Multifamily',
    'location'  => 'Coachella Valley, CA',
    'scope'     => 'Floor + roof trusses, phased delivery',
    'sqft'      => '52,000 sq ft',
    'completion'=> '[Year]',
    'builder'   => '[Builder name]',
    'architect' => '[Architect name]',
    'challenge' => 'Forty-eight units on an aggressive framing schedule where one late truss package would have stacked delays across every building.',
    'solution'  => 'Fabrication and delivery phased by building to match the framing sequence — every package on site the day the crew needed it.',
    'img'       => '/wp-content/uploads/2026/08/Project04.jpg',
  ),
  array(
    'title'     => 'Mixed-Use Corner Development',
    'category'  => 'Multifamily',
    'location'  => 'San Diego County, CA',
    'scope'     => 'Structural engineering + roof systems',
    'sqft'      => '28,500 sq ft',
    'completion'=> '[Year]',
    'builder'   => '[Builder name]',
    'architect' => '[Architect name]',
    'challenge' => 'Retail below, residential above: two structural logics meeting at one transfer level, with MEP fighting for every inch of the floor system.',
    'solution'  => 'Open-web floor trusses with MEP routing designed in, coordinated directly with the mechanical engineer before fabrication.',
    'img'       => '/wp-content/uploads/2026/08/Project05-scaled.jpg',
  ),
  array(
    'title'     => 'Vaulted Great Room Estate',
    'category'  => 'Custom Architecture',
    'location'  => 'Orange County, CA',
    'scope'     => 'Custom roof trusses, engineered + delivered',
    'sqft'      => '7,200 sq ft',
    'completion'=> '[Year]',
    'builder'   => '[Builder name]',
    'architect' => '[Architect name]',
    'challenge' => 'A 32-foot clear-span vaulted great room the original fabricator declined to quote.',
    'solution'  => 'Founder-led engineering resolved the geometry with a custom scissor system — engineered, fabricated and delivered by one accountable team.',
    'img'       => '/wp-content/uploads/2026/08/Project06.jpg',
  ),
);
